# Generated by Django 4.1.1 on 2022-09-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                ("code", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="NetworkMobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("g2", models.BooleanField(verbose_name="2G")),
                ("g3", models.BooleanField(verbose_name="3G")),
                ("g4", models.BooleanField(verbose_name="4G")),
                ("coordinate_x", models.FloatField(null=True)),
                ("coordinate_y", models.FloatField(null=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="src.network"
                    ),
                ),
            ],
        ),
    ]
